[2024-11-26T11:52:03.859+0200] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-26T11:52:03.869+0200] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: continuous_patient_data_generation.fetch_existing_patients scheduled__2024-11-26T09:51:00+00:00 [queued]>
[2024-11-26T11:52:03.876+0200] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: continuous_patient_data_generation.fetch_existing_patients scheduled__2024-11-26T09:51:00+00:00 [queued]>
[2024-11-26T11:52:03.876+0200] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-26T11:52:03.893+0200] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_existing_patients> on 2024-11-26 09:51:00+00:00
[2024-11-26T11:52:03.899+0200] {standard_task_runner.py:72} INFO - Started process 701304 to run task
[2024-11-26T11:52:03.905+0200] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'continuous_patient_data_generation', 'fetch_existing_patients', 'scheduled__2024-11-26T09:51:00+00:00', '--job-id', '1582', '--raw', '--subdir', 'DAGS_FOLDER/real_time_patient_data_update.py', '--cfg-path', '/tmp/tmpg62f2wnp']
[2024-11-26T11:52:03.906+0200] {standard_task_runner.py:105} INFO - Job 1582: Subtask fetch_existing_patients
[2024-11-26T11:52:03.947+0200] {task_command.py:467} INFO - Running <TaskInstance: continuous_patient_data_generation.fetch_existing_patients scheduled__2024-11-26T09:51:00+00:00 [running]> on host munyah-ThinkPad-X1-Yoga-1st
[2024-11-26T11:52:04.019+0200] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='munyah' AIRFLOW_CTX_DAG_ID='continuous_patient_data_generation' AIRFLOW_CTX_TASK_ID='fetch_existing_patients' AIRFLOW_CTX_EXECUTION_DATE='2024-11-26T09:51:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-26T09:51:00+00:00'
[2024-11-26T11:52:04.020+0200] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-26T11:52:04.020+0200] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-26T11:52:04.020+0200] {logging_mixin.py:190} INFO - Current task name:fetch_existing_patients state:running start_date:2024-11-26 09:52:03.870263+00:00
[2024-11-26T11:52:04.021+0200] {logging_mixin.py:190} INFO - Dag name:continuous_patient_data_generation and current dag run status:running
[2024-11-26T11:52:04.021+0200] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-26T11:52:04.027+0200] {base.py:84} INFO - Retrieving connection 'patients_data'
[2024-11-26T11:52:04.030+0200] {http.py:248} WARNING - HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/patient-data (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faa55071f90>: Failed to establish a new connection: [Errno 111] Connection refused')) Tenacity will retry to execute the operation
[2024-11-26T11:52:04.030+0200] {real_time_patient_data_update.py:50} ERROR - Exception during API fetch: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/patient-data (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faa55071f90>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-11-26T11:52:04.039+0200] {python.py:240} INFO - Done. Returned value was: None
[2024-11-26T11:52:04.046+0200] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-26T11:52:04.046+0200] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=continuous_patient_data_generation, task_id=fetch_existing_patients, run_id=scheduled__2024-11-26T09:51:00+00:00, execution_date=20241126T095100, start_date=20241126T095203, end_date=20241126T095204
[2024-11-26T11:52:04.055+0200] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-26T11:52:04.056+0200] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-26T11:52:04.056+0200] {logging_mixin.py:190} INFO - Dag name:continuous_patient_data_generation queued_at:2024-11-26 09:52:01.445228+00:00
[2024-11-26T11:52:04.056+0200] {logging_mixin.py:190} INFO - Task hostname:munyah-ThinkPad-X1-Yoga-1st operator:PythonOperator
[2024-11-26T11:52:04.076+0200] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-26T11:52:04.094+0200] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-26T11:52:04.097+0200] {local_task_job_runner.py:245} INFO - ::endgroup::
