[2024-11-26T16:07:03.924+0200] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-26T16:07:03.934+0200] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: continuous_patient_data_generation.fetch_existing_patients scheduled__2024-11-26T14:06:00+00:00 [queued]>
[2024-11-26T16:07:03.941+0200] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: continuous_patient_data_generation.fetch_existing_patients scheduled__2024-11-26T14:06:00+00:00 [queued]>
[2024-11-26T16:07:03.941+0200] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-26T16:07:03.954+0200] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_existing_patients> on 2024-11-26 14:06:00+00:00
[2024-11-26T16:07:03.959+0200] {standard_task_runner.py:72} INFO - Started process 754663 to run task
[2024-11-26T16:07:03.963+0200] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'continuous_patient_data_generation', 'fetch_existing_patients', 'scheduled__2024-11-26T14:06:00+00:00', '--job-id', '2092', '--raw', '--subdir', 'DAGS_FOLDER/real_time_patient_data_update.py', '--cfg-path', '/tmp/tmpzu4qidvg']
[2024-11-26T16:07:03.964+0200] {standard_task_runner.py:105} INFO - Job 2092: Subtask fetch_existing_patients
[2024-11-26T16:07:04.004+0200] {task_command.py:467} INFO - Running <TaskInstance: continuous_patient_data_generation.fetch_existing_patients scheduled__2024-11-26T14:06:00+00:00 [running]> on host munyah-ThinkPad-X1-Yoga-1st
[2024-11-26T16:07:04.081+0200] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='munyah' AIRFLOW_CTX_DAG_ID='continuous_patient_data_generation' AIRFLOW_CTX_TASK_ID='fetch_existing_patients' AIRFLOW_CTX_EXECUTION_DATE='2024-11-26T14:06:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-26T14:06:00+00:00'
[2024-11-26T16:07:04.082+0200] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-26T16:07:04.082+0200] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-26T16:07:04.083+0200] {logging_mixin.py:190} INFO - Current task name:fetch_existing_patients state:running start_date:2024-11-26 14:07:03.935146+00:00
[2024-11-26T16:07:04.083+0200] {logging_mixin.py:190} INFO - Dag name:continuous_patient_data_generation and current dag run status:running
[2024-11-26T16:07:04.083+0200] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-26T16:07:04.090+0200] {base.py:84} INFO - Retrieving connection 'patients_data'
[2024-11-26T16:07:04.094+0200] {http.py:248} WARNING - HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/patient-data (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7325f90ddbd0>: Failed to establish a new connection: [Errno 111] Connection refused')) Tenacity will retry to execute the operation
[2024-11-26T16:07:04.094+0200] {real_time_patient_data_update.py:50} ERROR - Exception during API fetch: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/patient-data (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7325f90ddbd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-11-26T16:07:04.106+0200] {python.py:240} INFO - Done. Returned value was: None
[2024-11-26T16:07:04.111+0200] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-26T16:07:04.112+0200] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=continuous_patient_data_generation, task_id=fetch_existing_patients, run_id=scheduled__2024-11-26T14:06:00+00:00, execution_date=20241126T140600, start_date=20241126T140703, end_date=20241126T140704
[2024-11-26T16:07:04.122+0200] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-26T16:07:04.123+0200] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-26T16:07:04.123+0200] {logging_mixin.py:190} INFO - Dag name:continuous_patient_data_generation queued_at:2024-11-26 14:07:01.559869+00:00
[2024-11-26T16:07:04.123+0200] {logging_mixin.py:190} INFO - Task hostname:munyah-ThinkPad-X1-Yoga-1st operator:PythonOperator
[2024-11-26T16:07:04.135+0200] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-26T16:07:04.154+0200] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-26T16:07:04.159+0200] {local_task_job_runner.py:245} INFO - ::endgroup::
