[2024-11-23T18:35:08.966+0200] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-23T18:35:08.983+0200] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: real_time_patient_data_update.fetch_new_patient_data scheduled__2024-11-23T16:30:00+00:00 [queued]>
[2024-11-23T18:35:08.992+0200] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: real_time_patient_data_update.fetch_new_patient_data scheduled__2024-11-23T16:30:00+00:00 [queued]>
[2024-11-23T18:35:08.992+0200] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-23T18:35:09.007+0200] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_new_patient_data> on 2024-11-23 16:30:00+00:00
[2024-11-23T18:35:09.013+0200] {standard_task_runner.py:72} INFO - Started process 397193 to run task
[2024-11-23T18:35:09.018+0200] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'real_time_patient_data_update', 'fetch_new_patient_data', 'scheduled__2024-11-23T16:30:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/real_time_patient_data_update.py', '--cfg-path', '/tmp/tmprxw1sto5']
[2024-11-23T18:35:09.020+0200] {standard_task_runner.py:105} INFO - Job 7: Subtask fetch_new_patient_data
[2024-11-23T18:35:09.070+0200] {task_command.py:467} INFO - Running <TaskInstance: real_time_patient_data_update.fetch_new_patient_data scheduled__2024-11-23T16:30:00+00:00 [running]> on host munyah-ThinkPad-X1-Yoga-1st
[2024-11-23T18:35:09.144+0200] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='real_time_patient_data_update' AIRFLOW_CTX_TASK_ID='fetch_new_patient_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-23T16:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-23T16:30:00+00:00'
[2024-11-23T18:35:09.146+0200] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-23T18:35:09.146+0200] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-23T18:35:09.147+0200] {logging_mixin.py:190} INFO - Current task name:fetch_new_patient_data state:running start_date:2024-11-23 16:35:08.983498+00:00
[2024-11-23T18:35:09.147+0200] {logging_mixin.py:190} INFO - Dag name:real_time_patient_data_update and current dag run status:running
[2024-11-23T18:35:09.147+0200] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-23T18:35:09.167+0200] {base.py:84} INFO - Retrieving connection 'patients_data'
[2024-11-23T18:35:09.180+0200] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/munyah/airflow/dags/real_time_patient_data_update.py", line 34, in fetch_new_patient_data
    if new_patient['id'] == existing_patient['id']:
KeyError: 'id'
[2024-11-23T18:35:09.193+0200] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-23T18:35:09.194+0200] {logging_mixin.py:190} INFO - Task start:2024-11-23 16:35:08.983498+00:00 end:2024-11-23 16:35:09.192680+00:00 duration:0.209182
[2024-11-23T18:35:09.194+0200] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_new_patient_data> dag:<DAG: real_time_patient_data_update> dagrun:<DagRun real_time_patient_data_update @ 2024-11-23 16:30:00+00:00: scheduled__2024-11-23T16:30:00+00:00, state:running, queued_at: 2024-11-23 16:35:01.816310+00:00. externally triggered: False>
[2024-11-23T18:35:09.195+0200] {logging_mixin.py:190} INFO - Failure caused by 'id'
[2024-11-23T18:35:09.195+0200] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=real_time_patient_data_update, task_id=fetch_new_patient_data, run_id=scheduled__2024-11-23T16:30:00+00:00, execution_date=20241123T163000, start_date=20241123T163508, end_date=20241123T163509
[2024-11-23T18:35:09.216+0200] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-23T18:35:09.217+0200] {standard_task_runner.py:124} ERROR - Failed to execute job 7 for task fetch_new_patient_data ('id'; 397193)
Traceback (most recent call last):
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/munyah/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/munyah/airflow/dags/real_time_patient_data_update.py", line 34, in fetch_new_patient_data
    if new_patient['id'] == existing_patient['id']:
KeyError: 'id'
[2024-11-23T18:35:09.229+0200] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-23T18:35:09.255+0200] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-23T18:35:09.256+0200] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-11-23T18:36:37.808+0200] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-23T18:36:37.827+0200] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: real_time_patient_data_update.fetch_new_patient_data scheduled__2024-11-23T16:30:00+00:00 [queued]>
[2024-11-23T18:36:37.840+0200] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: real_time_patient_data_update.fetch_new_patient_data scheduled__2024-11-23T16:30:00+00:00 [queued]>
[2024-11-23T18:36:37.840+0200] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-23T18:36:37.862+0200] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_new_patient_data> on 2024-11-23 16:30:00+00:00
[2024-11-23T18:36:37.872+0200] {standard_task_runner.py:72} INFO - Started process 397552 to run task
[2024-11-23T18:36:37.888+0200] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'real_time_patient_data_update', 'fetch_new_patient_data', 'scheduled__2024-11-23T16:30:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/real_time_patient_data_update.py', '--cfg-path', '/tmp/tmpkn1l7anx']
[2024-11-23T18:36:37.891+0200] {standard_task_runner.py:105} INFO - Job 4: Subtask fetch_new_patient_data
[2024-11-23T18:36:37.948+0200] {task_command.py:467} INFO - Running <TaskInstance: real_time_patient_data_update.fetch_new_patient_data scheduled__2024-11-23T16:30:00+00:00 [running]> on host munyah-ThinkPad-X1-Yoga-1st
[2024-11-23T18:36:38.056+0200] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='real_time_patient_data_update' AIRFLOW_CTX_TASK_ID='fetch_new_patient_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-23T16:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-23T16:30:00+00:00'
[2024-11-23T18:36:38.058+0200] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-23T18:36:38.058+0200] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-23T18:36:38.059+0200] {logging_mixin.py:190} INFO - Current task name:fetch_new_patient_data state:running start_date:2024-11-23 16:36:37.827935+00:00
[2024-11-23T18:36:38.059+0200] {logging_mixin.py:190} INFO - Dag name:real_time_patient_data_update and current dag run status:running
[2024-11-23T18:36:38.060+0200] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-23T18:36:38.080+0200] {base.py:84} INFO - Retrieving connection 'patients_data'
[2024-11-23T18:36:38.156+0200] {python.py:240} INFO - Done. Returned value was: None
[2024-11-23T18:36:38.164+0200] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-23T18:36:38.165+0200] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=real_time_patient_data_update, task_id=fetch_new_patient_data, run_id=scheduled__2024-11-23T16:30:00+00:00, execution_date=20241123T163000, start_date=20241123T163637, end_date=20241123T163638
[2024-11-23T18:36:38.178+0200] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-23T18:36:38.179+0200] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-23T18:36:38.179+0200] {logging_mixin.py:190} INFO - Dag name:real_time_patient_data_update queued_at:2024-11-23 16:36:24.569304+00:00
[2024-11-23T18:36:38.179+0200] {logging_mixin.py:190} INFO - Task hostname:munyah-ThinkPad-X1-Yoga-1st operator:PythonOperator
[2024-11-23T18:36:38.228+0200] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-23T18:36:38.249+0200] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-23T18:36:38.250+0200] {local_task_job_runner.py:245} INFO - ::endgroup::
